### ISSUE TITLE
no luck with kubectl apply -- group map is already registered

### ISSUE THREAD

**Issue by vjcitn** [mtmorgan/k8s-redis-bioc-example#1]
%vjcair> kubectl apply -f k8s/
error: group map[certificates.k8s.io:0xc4203cea80 federation:0xc4203ce0e0 :0xc4203ce5b0 autoscaling:0xc4203ce850 authorization.k8s.io:0xc4203ce7e0 batch:0xc4203cea10 policy:0xc42004e150 extensions:0xc42004e070 rbac.authorization.k8s.io:0xc42004e1c0 apps:0xc4203ce620 authentication.k8s.io:0xc4203ce690 componentconfig:0xc4203ceaf0 storage.k8s.io:0xc42004e230 scheduling.k8s.io:0xc4202dea10] is already registered

**Comment by mtmorgan** [comment]
googling for `error: group map is already registered` points first to an old `kubectl version` (mine is 1.14)?

**Comment by vjcitn** [comment]
right bad version of kubectl
