### ISSUE TITLE
bplapply hangs (run from command line)

### ISSUE THREAD

**Issue by vjcitn** [mtmorgan/k8s-redis-bioc-example#2]
> library(RedisParam)
Loading required package: BiocParallel
> 
> hostname = Sys.getenv("REDIS_SERVICE_HOST")
> port = as.integer(Sys.getenv("REDIS_SERVICE_PORT"))
> 
> p <- RedisParam(
+     workers = 5, jobname = "demo", is.worker = FALSE,
+     manager.hostname = hostname, manager.port = port
+ )
> register(bpstart(p))
> system.time(res <- bplapply(1:13, fun))

^C  # needed to kill

**Comment by vjcitn** [comment]
within Rstudio, i have

```
library(RedisParam)
Loading required package: BiocParallel
> 
> hostname = Sys.getenv("REDIS_SERVICE_HOST")
> port = as.integer(Sys.getenv("REDIS_SERVICE_PORT"))
> 
> p <- RedisParam(
+     workers = 5, jobname = "demo", is.worker = FALSE,
+     manager.hostname = hostname, manager.port = port
+ )
> register(bpstart(p))
Error in value[[3L]](cond) : 'redis' not available:
  Failed to create context: Servname not supported for ai_socktype
```

**Comment by mtmorgan** [comment]
Follow the updated 'manager.R' script in /home/rstudio -- no longer any need for hostname / port setting...

**Comment by vjcitn** [comment]
The code in README.md and /home/rstudio/manager.R all work after update.  I will mention that
on my first attempt, there was a hang owing to failure to ```kubectl delete -f k8s/``` after previous attempt.
